baseURL = 'https://rwxd.eu/'
languageCode = 'en-us'
title = 'rwxd.eu'
theme = 'hello-friend-ng'

enableRobotsTXT = true


[author]
  name = "rwxd"

[params]
  enableThemeToggle = true


  [[params.social]]
    name = "github"
    url = "https://github.com/rwxd"

  [[params.social]]
    name = "email"
    url = "mailto:rwxd@pm.me"

  [[params.social]]
    name = "wiki"
    url = "https://wiki.rwxd.eu/"

[menu]
  [[menu.main]]
      identifier = "wiki"
      name       = "Wiki"
      url        = "https://wiki.rwxd.eu/"
